version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      # TODO : database configs here
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
