version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydb # should be sync with config.yaml
      POSTGRES_USER: myuser # should be sync with config.yaml
      POSTGRES_PASSWORD: mypassword # should be sync with config.yaml
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
