app:
  server:
    port: 7070

database:
  host: localhost
  port: 5432
  name: mydb
  user: myuser
  password: mypassword
  sslmode: disable

client:
  allowed:
    - http://localhost:3000
    - http://localhost:3001
