name: Push the latest version to DockerHub

on:
  pull_request:
    types:
      - opened
      - closed

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # TODO : add your dockerhub username and token to github secrets
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # TODO : incase your github repository is private
          # secrets: |
          #   GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}

      - name: Build and push latest
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # TODO : don't forget to rename the image name and tag
          tags: dockerUsername/repoName:tag
